# Generated by Django 4.2.4 on 2023-08-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_banner_remove_product_price_productattributes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttributes',
            new_name='ProductAttribute',
        ),
    ]
